# Generated by Django 3.2.7 on 2021-10-30 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20211030_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='mobile_money_channel',
            field=models.CharField(blank=True, choices=[('MPESA', 'Mpesa'), ('AIRTEL_MONEY', 'Airtel Money'), ('T_KASH', 'T Kash')], max_length=32),
        ),
        migrations.AlterField(
            model_name='payment',
            name='mobile_money_channel_type',
            field=models.CharField(blank=True, choices=[('BUY_GOODS_TILL', 'Buy Goods Till'), ('PAYBILL', 'Paybill')], max_length=32),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CHECK', 'Check'), ('CREDIT_CARD', 'Credit Card'), ('MOBILE_MONEY', 'Mobile Money'), ('CRYPTOCURRENCY', 'Cryptocurrency'), ('BARTERING', 'Bartering'), ('MONEY_ORDER', 'Money Order'), ('ACH_OR_WIRE_TRANSFER', 'Ach Or Wire Transfer')], default='CASH', max_length=32),
        ),
    ]
