# Generated by Django 3.2.7 on 2021-10-30 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20211029_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_type',
            field=models.CharField(blank=True, choices=[('SOLE_PROPRIETORSHIP', 'Sole Proprietorship'), ('PARTNERSHIP', 'Partnership'), ('LIMITED_LIABILITY_PARTNERSHIP', 'Limited Liability Partnership'), ('LIMITED_LIABILITY_COMPANY', 'Limited Liability Company'), ('SOCIETY', 'Society')], max_length=32),
        ),
        migrations.AlterField(
            model_name='business',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=32),
        ),
        migrations.AlterField(
            model_name='loanportfolio',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=16),
        ),
        migrations.AlterField(
            model_name='owner',
            name='gender',
            field=models.CharField(blank=True, choices=[('FEMALE', 'Female'), ('MALE', 'Male'), ('OTHER', 'Other')], max_length=16),
        ),
        migrations.AlterField(
            model_name='owner',
            name='identification_method',
            field=models.CharField(choices=[('NATIONAL_ID', 'National ID'), ('PASSPORT', 'Passport'), ('DRIVER_LICENSE', "Driver's License")], default='NATIONAL_ID', max_length=32),
        ),
        migrations.AlterField(
            model_name='owner',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('WIDOWED', 'Widowed'), ('DIVORCED', 'Divorced')], max_length=16),
        ),
    ]
