# Generated by Django 3.2.7 on 2021-10-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_rename_business_type_business_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='type',
            field=models.CharField(blank=True, choices=[('SOLE_PROPRIETORSHIP', 'Sole Proprietorship'), ('PARTNERSHIP', 'Partnership'), ('LIMITED_LIABILITY_PARTNERSHIP', 'Limited Liability Partnership'), ('LIMITED_LIABILITY_COMPANY', 'Limited Liability Company'), ('SOCIETY', 'Society')], max_length=64),
        ),
    ]
