# Generated by Django 3.2.7 on 2021-10-30 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_alter_business_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='type',
            new_name='business_type',
        ),
    ]
