# Generated by Django 3.2.7 on 2021-11-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_alter_business_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='category',
            field=models.CharField(blank=True, choices=[('ACCOUNTING', 'Accounting'), ('AGENTS', 'Agents'), ('AGRICULTURE', 'Agriculture'), ('ANTIQUES_AND_COLLECTABLES', 'Antiques and Collectables'), ('ARTS_AND_CRAFTS', 'Arts and Crafts'), ('ASSET_MANAGEMENT', 'Assets Management'), ('AUTOMOTIVE', 'Automotive'), ('BEVERAGES', 'Beverages'), ('BROKERS', 'Brokers'), ('BUSINESS_SERVICES', 'Business Services'), ('CHILD_CARE', 'Child Care'), ('CLEANING_SERVICES', 'Cleaning Services'), ('DESIGN', 'Design'), ('DISTRIBUTOR', 'Distributor'), ('ECOMMERCE', 'Ecommerce'), ('EDUCATION_AND_TRAINING', 'Education and Training'), ('ENTERTAINMENT', 'Entertainment'), ('FASHION', 'Fashion'), ('FOOD_SERVICES', 'Food Sevices'), ('GARDENING_AND_LANDSCAPING', 'Gardening and Landscaping'), ('HEALTH_AND_BEAUTY', 'Health and Beauty'), ('INFORMATION_TECHNOLOGY', 'Information Technology'), ('LEGAL_SERVICES', 'Legal Services'), ('MAINTENANCE_AND_REPAIR', 'Maintenance and Repair'), ('MANAGEMENT_SERVICES', 'Management Services'), ('MANUFACTURING', 'Manufacturing'), ('MARKETING_SERVICES', 'Marketing Services'), ('MEDIA', 'Media'), ('MEDICAL_PRACTITIONERS', 'Medical Practitioners'), ('MUSIC', 'Music'), ('NIGHTLIFE', 'Nightlife'), ('PERSONAL_SERVICES', 'Personal Services'), ('PET_SERVICES', 'Pet Services'), ('PHOTOGRAPHY', 'Photography'), ('PROFESSIONAL_SERVICES', 'Professional Services'), ('PUBLISHING', 'Publishing'), ('RECRUITING_AND_STAFFING', 'Recruiting and Staffing'), ('RENTAL_AND_LEASING', 'Rental and Leasing'), ('RESEARCH_SERVICES', 'Research Services'), ('RETAIL', 'Retail'), ('SHIPPING_AND_DELIVERY', 'Shipping and Delivery'), ('SPORTS_AND_RECREATION', 'Sports and Recreation'), ('TOYS_AND_HOBBIES', 'Toys and Hobbies'), ('TRANSPORTATION', 'Transportation'), ('TRAVEL_AND_TOURISM', 'Travel and Tourism'), ('VALUE_ADDED_RESELLER', 'Value Added Reseller'), ('WAREHOUSING_AND_STORAGE', 'Warehousing and Storage'), ('WHOLESALE', 'Wholesale')], max_length=255),
        ),
    ]
