version: "3.9"

services:
  web:
    build: .
    command: ./manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/schmsoft
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db
    container_name: web
  db:
    image: postgres
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    container_name: db
volumes:
  database:
