version: "3.9"
volumes:
  - ipython_data_local: {}
services:
  web:
    build: .
    command: ./manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/schmsoft
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db
    container_name: schmsoft-web
  db:
    image: postgres
    volumes:
      - ./database:/var/lib/postgresql/data
      - ./ipython_data_local:/root/.ipython/profile_default
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_PORT=$POSTGRES_PORT
      - SLACK_NOTIFICATIONS_CHANNEL=$SLACK_NOTIFICATIONS_CHANNEL
      - SLACK_BOT_TOKEN=$SLACK_BOT_TOKEN
      - DEBUG=$DEBUG
    container_name: schmsoft-db
volumes:
  database:
