version: "3.9"
volumes:
  ipython_data_local: {}
  database: null
services:
  db:
    image: postgres
    volumes:
      - ./database:/var/lib/postgresql/data
      - ./ipython_data_local:/root/.ipython/profile_default
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_HOST=$POSTGRES_HOST
    container_name: schmsoft-db
  web:
    build: .
    environment:
      - SECRET_KEY=$SECRET_KEY
      - DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
      - SLACK_BOT_TOKEN=$SLACK_BOT_TOKEN
      - MONYERA_USERNAME=$MONYERA_USERNAME
      - MONYERA_PASSWORD=$MONYERA_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_HOST=$POSTGRES_HOST
    command: ./manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/schmsoft
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db
    container_name: schmsoft-web
