# Generated by Django 3.2.7 on 2021-10-29 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('mechanism', models.CharField(choices=[('Text Message', 'Sms'), ('Email', 'Email'), ('Slack', 'Slack')], db_index=True, max_length=32)),
                ('sent_from_email_address', models.EmailField(blank=True, max_length=200)),
                ('sent_to_email_address', models.EmailField(blank=True, max_length=200)),
                ('sent_to_phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('sent_from_sender_id', models.CharField(blank=True, max_length=11)),
                ('sent_to_slack_username_or_channel', models.CharField(blank=True, max_length=64)),
                ('definition_key', models.CharField(db_index=True, max_length=64)),
                ('subject', models.CharField(blank=True, max_length=256)),
                ('text_content', models.TextField()),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contacts_sent', to=settings.AUTH_USER_MODEL)),
                ('sent_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contacts_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
