# Generated by Django 3.2.7 on 2021-10-30 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrecord',
            name='mechanism',
            field=models.CharField(choices=[('SMS', 'Text Message'), ('EMAIL', 'Email'), ('SLACK', 'Slack')], db_index=True, max_length=32),
        ),
    ]
