# Generated by Django 3.2.7 on 2021-11-06 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_contactrecord_mechanism'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrecord',
            name='mechanism',
            field=models.CharField(choices=[('SMS', 'Text Message (SMS)'), ('EMAIL', 'Email'), ('SLACK', 'Slack')], db_index=True, max_length=32),
        ),
    ]
