# Generated by Django 3.2.7 on 2021-11-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_contactrecord_mechanism'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrecord',
            name='succeeded',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
