# Generated by Django 3.2.7 on 2021-11-29 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_contactrecord_succeeded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrecord',
            name='definition_key',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
